<?php

namespace Database\Seeders;

use App\Models\AssignmentType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AssignmentTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assignmentTypes = self::ASSIGNMENT_TYPES;
        foreach ($assignmentTypes as $assignmentType) {
            AssignmentType::create([
                'assignment_type_name' => $assignmentType,
            ]);
        }
    }

    const ASSIGNMENT_TYPES = [
        'Homework',
        'Quiz',
        'Project',
        'Essay',
        'Midterm Exam',
        'Final Exam',
        'Presentation',
        'Group Work',
        'Lab Report',
        'Discussion Forum',
        'Research Paper',
        'Case Study',
        'Online Test',
        'Peer Review',
        'Group Presentation',
        'Problem Set',
        'Portfolio',
        'Take-Home Exam',
        'Class Participation',
        'Individual Presentation',
        'Group Discussion',
        'Group Assignment',
        'Worksheet',
        'Peer Assessment',
        'Journal Entry',
        'Online Discussion',
        'Team Project',
        'Reflection Paper',
        'Practical Exam',
        'In-Class Exercise',
        'Video Presentation',
        'Oral Examination',
        'Simulated Scenario',
        'Field Work Report',
        'Coding Assignment',
        'Math Exercise',
        'Simulation Assignment',
        'Artistic Creation',
        'Field Observation',
        'Literature Review',
        'Problem-Solving Task',
        'Music Composition',
        'Group Research',
        'Code Review',
        'Lab Experiment',
        'Data Analysis',
        'Simulation Project',
        'Field Research',
        'Design Challenge',
        'Performance Task',
        'Critical Analysis',
        'Peer Feedback',
        'Simulation Exercise',
        'Industry Report',
        'Interactive Assignment',
        'Observation Report',
        'Technical Report',
        'Group Coding Project',
        'Design Portfolio',
        'Peer Presentation',
        'Project Evaluation',
        'Group Problem Solving',
        'Group Simulation',
        'Model Building',
        'Role-Play Exercise',
        'Field Study',
        'Simulated Business Plan',
        'Portfolio Assessment',
        'Creative Writing',
        'Case Analysis',
        'Group Coding Challenge',
        'Oral Presentation',
        'Model Simulation',
        'Virtual Lab Experiment',
        'Group Field Work',
        'Performance Assessment',
        'Coding Challenge',
        'Design Project',
        'Lab Simulation',
        'Field Investigation',
        'Business Simulation',
        'Modeling Assignment',
        'Business Proposal',
        'Group Coding Exercise',
        'Peer Evaluation',
        'Peer Discussion',
        'Group Problem Solving',
        'Field Trip Report',
        'Design Task',
        'Project Proposal',
        'Industry Analysis',
        'Group Business Plan',
        'Technical Assignment',
        'Coding Project',
        'Research Proposal',
        'Art Project',
        'Experiment Report',
        'Field Evaluation',
        'Business Report',
        'Design Exercise',
        'Group Design Challenge',
        'Modeling Project',
        'Interactive Exercise',
        'Group Performance Task',
        'Simulation Report',
        'Simulation Task',
        'Business Case Study',
        'Modeling Exercise',
        'Peer Workshop',
        'Coding Task',
        'Design Challenge',
        'Technical Problem',
        'Business Task',
        'Role-Play Assignment',
        'Virtual Experiment',
        'Modeling Challenge',
        'Coding Challenge',
        'Group Coding Task',
        'Simulation Challenge',
        'Business Simulation Task',
        'Interactive Simulation',
        'Design Simulation',
        'Field Experiment',
        'Coding Experiment',
        'Modeling Task',
        'Performance Assessment',
        'Business Strategy',
        'Technical Challenge',
        'Field Assignment',
        'Coding Workshop',
        'Simulation Workshop',
        'Role-Play Simulation',
        'Group Experiment',
        'Virtual Business Plan',
        'Modeling Workshop',
        'Coding Simulation',
        'Business Pitch',
        'Field Challenge',
        'Design Workshop',
        'Simulation Exercise',
        'Coding Challenge',
        'Technical Simulation',
        'Coding Simulation',
        'Business Workshop',
        'Role-Play Workshop',
        'Modeling Simulation',
        'Virtual Challenge',
        'Technical Workshop',
        'Field Workshop',
        'Coding Task',
        'Role-Play Challenge',
        'Simulation Task',
        'Design Task',
        'Business Task',
        'Modeling Task',
        'Virtual Task',
        'Technical Task',
        'Field Task',
        'Coding Exercise',
        'Role-Play Task',
        'Simulation Challenge',
        'Design Challenge',
        'Business Challenge',
        'Modeling Challenge',
        'Virtual Exercise',
        'Technical Exercise',
        'Field Challenge',
        'Coding Workshop',
        'Role-Play Exercise',
        'Simulation Workshop',
        'Design Workshop',
        'Business Exercise',
        'Modeling Exercise',
        'Virtual Workshop',
        'Technical Workshop',
        'Field Exercise',
    ];
}
