<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::COURSES as $course) {
            Course::factory()->create([
                'course_name' => $course,
                'qualification' => self::QUALIFICATIONS[array_rand(self::QUALIFICATIONS)],
            ]);
        }
    }

    const QUALIFICATIONS = [
        'Bachelor of Science (B.Sc.)',
        'Bachelor of Arts (B.A.)',
        'Master of Science (M.Sc.)',
        'Master of Arts (M.A.)',
        'Doctor of Philosophy (Ph.D.)',
        'Associate of Arts (A.A.)',
        'Associate of Science (A.S.)',
        'Diploma in Business Administration',
        'Certificate in Web Development',
        'Postgraduate Diploma in Education',
        'Bachelor of Engineering (B.Eng.)',
        'Master of Business Administration (MBA)',
        'Doctor of Medicine (M.D.)',
        'Juris Doctor (J.D.)',
        'Bachelor of Fine Arts (B.F.A.)',
        'Certificate in Graphic Design',
        'Advanced Diploma in Nursing',
        'Bachelor of Commerce (B.Com.)',
        'Master of Social Work (MSW)',
        'Certificate in Digital Marketing',
        'Diploma in Culinary Arts',
        'Associate Degree in Information Technology',
        'Postgraduate Certificate in Finance',
        'Bachelor of Architecture (B.Arch.)',
        'Master of Public Health (MPH)',
        'Doctor of Dental Medicine (DMD)',
        'Bachelor of Pharmacy (B.Pharm.)',
        'Master of Physics (M.Phys.)',
        'Certificate in Data Science',
        'Diploma in Environmental Studies',
        'Associate Degree in Hospitality Management',
        'Postgraduate Diploma in Psychology',
        'Bachelor of Music (B.Mus.)',
        'Master of Computer Science (MCS)',
        'Doctor of Veterinary Medicine (DVM)',
        'Bachelor of Physical Therapy (BPT)',
        'Master of Optometry (MOptom)',
        'Certificate in Public Relations',
        'Diploma in Counseling',
        'Associate Degree in Theater Arts',
        'Postgraduate Certificate in Marketing',
        'Bachelor of Information Technology (BIT)',
        'Master of Data Analytics (MDA)',
        'Doctor of Psychology (Psy.D.)',
        'Bachelor of Dance (B.Dance)',
        'Certificate in Sports Management',
        'Advanced Diploma in Hotel Administration',
        'Bachelor of Nursing (B.N.)',
        'Master of Dentistry (MDent)',
        'Doctor of Pharmacy (Pharm.D.)',
        'Bachelor of Geology (B.Geol.)',
        'Master of Environmental Science (MES)',
        'Certificate in Fashion Design',
        'Diploma in Interior Design',
        'Associate Degree in Criminal Justice',
        'Postgraduate Diploma in Human Resources',
    ];

    const COURSES = [
        'Introduction to Mathematics',
        'Biology Fundamentals',
        'History of Ancient Civilizations',
        'Literary Analysis and Criticism',
        'Programming Fundamentals in Python',
        'Art Appreciation',
        'Music Theory and Composition',
        'Physical Education and Fitness',
        'French Language for Beginners',
        'Business Management Principles',
        'Introduction to Mechanical Engineering',
        'Anatomy and Physiology',
        'Legal Studies and Ethics',
        'Introduction to Psychology',
        'Foundations of Education',
        'Environmental Science and Sustainability',
        'Philosophy of Ethics',
        'Culinary Arts and Cooking Techniques',
        'Architectural Design and Planning',
        'Film Production and Cinematography',
        'Graphic Design Essentials',
        'Health and Wellness Strategies',
        'Marketing Strategies and Advertising',
        'Microeconomics and Macroeconomics',
        'Political Science and Government',
        'Sociology of Society',
        'Communication Skills and Public Speaking',
        'Theater Arts and Performance',
        'Religious Studies and Comparative Religion',
        'Astronomy and Astrophysics',
        'Geography of World Regions',
        'Cultural Anthropology',
        'Sports Management and Administration',
        'Hospitality and Hotel Management',
        'Nursing Fundamentals',
        'Dental Hygiene and Care',
        'Pharmacy Technician Training',
        'Physics for Scientists and Engineers',
        'Chemistry Laboratory Techniques',
        'Biology Research and Lab Work',
        'Geology and Earth Sciences',
        'Environmental Studies and Conservation',
        'Agriculture and Crop Science',
        'Fashion Design and Clothing Construction',
        'Interior Design and Space Planning',
        'Psychiatry and Mental Health Studies',
        'Counseling and Psychotherapy',
        'Drama and Theater Production',
        'Dance Performance and Choreography',
        'Veterinary Medicine and Animal Care',
        'Physical Therapy Techniques',
        'Optometry and Eye Care',
        'Public Health and Epidemiology',
        'Information Technology Fundamentals',
        'Data Science and Analytics',
        'Machine Learning and AI Applications',
        'Cybersecurity and Network Security',
        'Game Development and Game Design',
        'Web Development and Programming',
        'Mobile App Development for iOS and Android',
    ];
}
